### ISSUE TITLE
Add login input area in Navbar 

### ISSUE THREAD

**Issue by dgghun** [VonHohenheim/LawyerUp#14]
All that is needed for now is email and password input fields so user can login. 
- [x] Have a login input on landing page.
- [x] Have a login input on lawyer signup page.
- [x] Have a login input on client signup page.

**Comment by VonHohenheim** [comment]
@dgghun 
Can you elaborate a little more?
- Are you saying you want text input boxes when a user clicks on the login button on index.html?
- Why would we need login fields from a client/lawyer signup page?

**Comment by dgghun** [comment]
@VonHohenheim 
Yeah just a login area in the Navbar. I was considering adding them on the sign up pages as well in case a user forgets they have an account or something. I am not married to the idea so if you think it will cleaner without them let me know. What about the index page though? Check out the image below. 
![image](https://user-images.githubusercontent.com/10663994/59004848-0480ad80-87d0-11e9-8d58-3f299af9b358.png)

**Comment by VonHohenheim** [comment]
@dgghun how do you want to manage logins? Do we want to do this ourselves or use something like Passport to validate using Google (or other) sign in? This wouldn't be in scope for this issue but its food for though if we want to go through the pains of building out our own middleware.

**Comment by dgghun** [comment]
If we go with Passport I would think we would still need a standard way of logging in que no?

**Comment by VonHohenheim** [comment]
Yup. It would be a nice "strong" feature to have OAuth authentication vs just using username/password authentication. It's a "nice to have" future development but nothing that we would need at the moment.

**Comment by VonHohenheim** [comment]
Added a modal for the login instead of just having the input boxes.
