### ISSUE TITLE
Readd video chat service

### ISSUE THREAD

**Issue by VonHohenheim** [VonHohenheim/LawyerUp#36]
- [ ] Reformat video chat view to Pug template
- [ ] Add dynamic pug variables that represent room numbers
- [ ] Add ability for client to access room after issue #13 is complete
- [ ] Add ability for lawyer to access room after issue #12 is complete

**Comment by dgghun** [comment]
This will have to be revisited since running into issue of dynamic rooms not connecting correctly.
