### ISSUE TITLE
Create Client user sign up page

### ISSUE THREAD

**Issue by VonHohenheim** [VonHohenheim/LawyerUp#4]
User should be able to sign up for an account.

- [x] Option to create account from landing page
 **NOTE: The below issues have been moved to issues #13 and #12** 
- [x] Have user information saved to DB
- [x] User is able to login and logout of website

**Comment by VonHohenheim** [comment]
- [ ] Option to create account from landing page
- [ ] Have user information saved to DB
- [ ] User is able to login and logout of webiste

**Comment by dgghun** [comment]
Is this issue similar to issue #3 Landing UI ? Could we split this into two issues with one handling the login info for a client and one for a lawyer since we would probably need different info from both down the road?

**Comment by VonHohenheim** [comment]
Sure thing.

**Comment by VonHohenheim** [comment]
@dgghun Do you think the sign in page should be a popup, Modal, or a separate page all together?

**Comment by dgghun** [comment]
Moved DB stuff to #13 and #12
