### ISSUE TITLE
Lawyer signup page

### ISSUE THREAD

**Issue by VonHohenheim** [VonHohenheim/LawyerUp#6]
User should be able to sign up for an account

- [x] Option to create account from landing page
 **NOTE: The below issues have been moved to issues #13 and #12** 
- [x] Have user information saved to DB
        - First name, Last name, state registered, type of practice,  etc.
- [x] User is able to login and logout of website

**Comment by dgghun** [comment]
I moved the DB stuff to #13  and #12
