### ISSUE TITLE
Add javascript hover effect to landing page "signup" boxes

### ISSUE THREAD

**Issue by VonHohenheim** [VonHohenheim/LawyerUp#8]
Thinking we need to add an effect to the two boxes that a user would click to signup. Something like a highlighting effect when the mouse is hovered over them. @dgghun what do you think.

**Comment by dgghun** [comment]
Yeah I like that sir. It would help signify that it is a clickable item.

**Comment by dgghun** [comment]
Created hover effect to bold and change color on text of sign up links.
