### ISSUE TITLE
Create database connection layer

### ISSUE THREAD

**Issue by VonHohenheim** [VonHohenheim/LawyerUp#9]
Create business/service layer to connect the MySQL DB to the application. Use DB setup file /test/lawyerup.sql

**Comment by VonHohenheim** [comment]
Use Sequelize for connection layer.

http://docs.sequelizejs.com/

**Comment by VonHohenheim** [comment]
For our CRUD we said we were going to split it up right?
dgghun
- [ ] Create
- [ ] Retrieve

VonHohenheim
- [ ] Update
- [ ] Delete

**Comment by dgghun** [comment]
Yeah correct sir

**Comment by VonHohenheim** [comment]
Taking myself off of this one.
